let data = [
    {
        id:"a",
        idd:'ab',
        AddToid:'abc',
        priceToid:'aq',
        img:"nike1-removebg-preview.png",
        name:'Green Blaster',
        price:300

    }
    ,
    {
        id:"b",
        idd:'bc',
        AddToid:'bcd',
        priceToid:'aw',
        img:"nike2-removebg-preview.png",
        name:'Merchant',
        price:300
    }
    ,
    {
        id:"c",
        idd:'cd',
        AddToid:'cde',
        priceToid:'ae',
        img:"nike_3-removebg-preview.png",
        name:'Blue Shoe',
        price:300
    }
    ,
    {
        id:"e",
        idd:'ef',
        AddToid:'efg',
        priceToid:'at',
        img:"nike4.webp",
        name:'Simple Style Shoes',
        price:300
    }
    ,
  
    {
        id:"d",
        idd:'de',
        AddToid:'def',
        priceToid:'ar',
        img:"nike12.jpg",
        name:'Pinky',
        price:300
    }
    ,
    {
        id:"f",
        idd:'fg',
        AddToid:'fgh',
        priceToid:'ay',
        img:"nike5.webp",
        name:'Green Fusion',
        price:300
    }
    ,
    {
        id:"g",
        idd:'gh',
        AddToid:'ghi',
        priceToid:'au',
        img:"blackshoe.webp",
        name:'Black March',
        price:300
    }
    ,
    {
        id:"h",
        idd:'hi',
        AddToid:'hij',
        priceToid:'ai',
        img:"nike6.png",
        name:'Magenta',
        price:300
    }
    ,
    {
        id:"i",
        idd:'ij',
        AddToid:'ijk',
        priceToid:'ao',
        img:"nike7.png",
        name:'Dragon Red',
        price:300
    }
    ,
    {
        id:"j",
        idd:'jk',
        AddToid:'jkl',
        priceToid:'ap',
        img:"nike8.jpg",
        name:'Mixy',
        price:300
    }
    ,
    {
        id:"k",
        idd:'kl',
        AddToid:'klm',
        priceToid:'as',
        img:"nike9.jpg",
        name:'Blue National',
        price:300
    }
    ,
    {
        id:"l",
        idd:'lm',
        AddToid:'lmn',
        priceToid:'ad',
        img:"nike10.jpg",
        name:'Orange Whity',
        price:300
    }
]
